### ISSUE TITLE
Will you instruct the steps to use this tool?

### ISSUE THREAD

**Issue by plr0201** [Ekey/ER.BDT.Tool#11]
Hi, Sir, nice tool! However, don't know how to use it. In visual studio? or directly in cmd (apparently not)? dotnet build doesn't work neither.

Looking forward to your response!

**Comment by Ekey** [comment]
Usage from cmd.

ER.Unpacker "**BHD_FILE**" "**UNPACK_DIRECTORY**"

**Example:**
ER.Unpacker "**E:\Games\Steam\steamapps\common\ELDEN RING\Game\Data0.bhd**" "**D:\Unpacked**"

**Comment by plr0201** [comment]
OMG. The answer is : https://github.com/Ekey/ER.BDT.Tool/releases
The exe file included in the release zip.
Thanks!
