### ISSUE TITLE
BDT tool unpacks unknown files

### ISSUE THREAD

**Issue by losh11** [Ekey/ER.BDT.Tool#13]
Expect BDT tool to unpack files into readable files, however the output folder created is called `__Unknown` and contains many files of differening sizes.

```
> C:\Users\...\Downloads\ER.BDT.Tool-0.1.41767\Release\ER.Unpacker.exe "E:\Games\SteamLibrary\steamapps\common\ELDEN RING\Game\Data0.bhd" "C:\Users\...\Desktop\ER"
ELDEN RING Binder Unpacker
(c) 2022 Ekey (h4x0r) / v0.0.1.41767

[WARNING]: Unable to load project file \Projects\FileNames.list!
[UNPACKING]: __Unknown\65522405ED07203C
[UNPACKING]: __Unknown\47610D32B872F5FF
[UNPACKING]: __Unknown\A2D5627CEBF2CEC6
[UNPACKING]: __Unknown\E4121558144AC804
[UNPACKING]: __Unknown\A14F84A3E60EA4CE
[UNPACKING]: __Unknown\ABA36FF55C3FAE23
[UNPACKING]: __Unknown\3DD06BA4CCF6EADF
[UNPACKING]: __Unknown\6B1ED54F02E412DC
[UNPACKING]: __Unknown\49756A55CA6C452D
[UNPACKING]: __Unknown\FCE3760FAD792E23
[UNPACKING]: __Unknown\9521C936862A2EF7
[UNPACKING]: __Unknown\1253407A71712EC2
[UNPACKING]: __Unknown\C1FE988158C55DED
[UNPACKING]: __Unknown\1992FEFDDFA121B5
...
```

**Comment by losh11** [comment]
I believe the game files list is out of date: https://github.com/Nordgaren/UXM-Selective-Unpack/blob/master/UXM/res/EldenRingDictionary.txt

@Ekey if possible would you be able to recompile with this new dictionary file?

**Comment by Ekey** [comment]
As I can see the tool cannot load the project file

`[WARNING]: Unable to load project file \Projects\FileNames.list!`

Move the folder with the tool to the root of drive C: or D: or E:
