### ISSUE TITLE
System.BadImageFormatException

### ISSUE THREAD

**Issue by TBulbaDB** [Ekey/ER.BDT.Tool#2]
Hi @Ekey,

When I run the tool, I get the following exception:

![image](https://user-images.githubusercontent.com/20840602/156877497-c47a406d-5d11-4fa0-b30b-8bd907f73419.png)

Any ideas how to fix it?

Thanks a lot for the tool.

**Comment by Ekey** [comment]
Are you sure that the project is compiled for x64 architecture?

**Comment by TBulbaDB** [comment]
That was the issue indeed, thanks again for the tool and the help.
