### ISSUE TITLE
About Unknown files

### ISSUE THREAD

**Issue by kzoacn** [Ekey/ER.BDT.Tool#3]
Most of them are BND file, except ``92FB1CEB78F552AD`` which is a PSC file.

I can unpack all BND files using BinderTool. The unpacked files contain lots of .ppo and .vpo files. It seems that they are shader and texture.

![untitile](https://user-images.githubusercontent.com/11485970/156887694-bfb128ad-b48c-46d6-9a8b-c41ec3ce9d32.png)

**Comment by Ekey** [comment]
Unknown files are bundles from the shader folder, probably unused or for debugging.
