### ISSUE TITLE
About regulation.bin

### ISSUE THREAD

**Issue by kzoacn** [Ekey/ER.BDT.Tool#4]
``regulation.bin`` is the regulation file for Elden Ring. ``Data0.bdt`` is a data file now, unlike previous DS3 etc.

I found a lot of parameters from the regulation file, just like other from software games.

**Comment by Ekey** [comment]
Well, decrypted file regulation.bin it is a bundle of the BND4 format and contains some binary data files (game settings i guess). Here decrypted file if someone needs.

[regulation.zip](https://github.com/Ekey/ER.BDT.Tool/files/8191036/regulation.zip)
