### ISSUE TITLE
hey I meet a "Not an rsa key" error

### ISSUE THREAD

**Issue by liguokai527** [Ekey/ER.BDT.Tool#7]
E:\Release>ER.UNPACKER.EXE "E:\ORIGIN\DATA0.BHD" "E:\UNPACKED"
ELDEN RING Binder Unpacker
(c) 2022 Ekey (h4x0r) / v0.0.1.41767

[INFO]: Project File Loaded: 88302

未经处理的异常:  Org.BouncyCastle.Security.InvalidKeyException: Not an RSA key
   在 Org.BouncyCastle.Crypto.Engines.RsaCoreEngine.Init(Boolean forEncryption, ICipherParameters parameters)
   在 ER.Unpacker.BinderCipher.iDecryptByRSA(String m_BinderFile)
   在 ER.Unpacker.BinderUnpack.iDoIt(String m_BinderFile, String m_DstFolder)
   在 ER.Unpacker.Program.Main(String[] args)

E:\Release>

several days ago it's work, but today on another pc, it just can't. Looking forward to your help, thank you~

**Comment by Ekey** [comment]
Hmm, really weird. Make sure that the executable, libraries (DLL's), BHD and BDT files are unlocked if you copied them from another computer.

**Comment by Farid20015** [comment]
D:\Release>ER.Unpacker "D:\sd\sd.bdt" "D:\ext"
ELDEN RING Binder Unpacker
(c) 2022 Ekey (h4x0r) / v0.0.1.41767

[INFO]: Project File Loaded: 88302


Unhandled Exception: Org.BouncyCastle.Crypto.DataLengthException: input too large for RSA cipher.
   at Org.BouncyCastle.Crypto.Engines.RsaCoreEngine.ConvertInput(Byte[] inBuf, Int32 inOff, Int32 inLen)
   at Org.BouncyCastle.Crypto.Engines.RsaEngine.ProcessBlock(Byte[] inBuf, Int32 inOff, Int32 inLen)
   at ER.Unpacker.BinderCipher.iDecryptByRSA(String m_BinderFile)
   at ER.Unpacker.BinderUnpack.iDoIt(String m_BinderFile, String m_DstFolder)
   at ER.Unpacker.Program.Main(String[] args)

**Comment by Ekey** [comment]
> D:\Release>ER.Unpacker "D:\sd\sd.bdt" "D:\ext"

You need specefy **BHD** file instead of **BDT**.

**Comment by liguokai527** [comment]
thank u for your patiently response, I just find it works on my own PC still. I believe the cause of the error is that I never run the game on my company computer so that the BHD file is still locked.
