### ISSUE TITLE
[ERROR]: Unable to initialize oo2core_6_win64.dll module. Copy this library from game folder!

### ISSUE THREAD

**Issue by milan-dlz** [Ekey/ER.BDT.Tool#8]
Hello!
I'm getting this error despite having copy-pasted oo2core_6_win64.dll in the unpacker folder, am I missing something?

**Comment by Ekey** [comment]
Make sure the executable and libraries (DLL's) files are unlocked if are using Windows 10

**Comment by milan-dlz** [comment]
Yep that dit it, thanks!
