### ISSUE TITLE
Round out file names

### ISSUE THREAD

**Issue by googleben** [Ekey/ER.BDT.Tool#9]
During my work on Binder Tool, I found all the file names for the current game version minus 12 weird ones that seem like near-identical duplicates of the data0 shader files. My fork is [here](https://github.com/googleben/BinderTool/tree/elden-ring). The file names are in `/BinderTool/DictionaryER.csv`, but they're stored with the alias roots the game uses (e.g. "map:/"). You can use a simple search-replace in a text editor or something or use the `FileNameDictionary.MakeHashable` function in Binder Tool - `FileNameDictionary` has a list of all the aliases used in DictionaryER as well as what they should be replaced with.

**Comment by Ekey** [comment]
> I found all the file names for the current game version

Oh great, thanks! Merged :)

> 12 weird ones that seem like near-identical duplicates of the data0 shader files.

These files are probably debug shader files like in DS3: 

```
/shader/debugfont.shaderbnd.dcx
/shader/gxflvershader.shaderbnd.dcx
/shader/gxflvershader.shaderbnddebug.dcx
/shader/shaderbdle.shaderbdlebnd.dcx
/shader/shaderbdle.shaderbdlebnddebug.dcx
```

We need to check the files from the retail PS4, as I see that the archives are not used console version

![1640976004243](https://user-images.githubusercontent.com/1664144/159326864-6d3f4af7-215d-46c0-84ef-cb63d621600f.png)
